OnlineShop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Models;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Admin
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private ApplicationDbContext db { get; set; }

        [System.Obsolete]
        private IHostingEnvironment _he;

        [System.Obsolete]
        public ProductController(ApplicationDbContext _db, IHostingEnvironment he)
        {
            db = _db;
            _he = he;
        }

        public IActionResult Index()
        {
            return View(db.Products.Include(c => c.ProductTypes).Include(f => f.SpecialTags).ToList());
        }
        //Action Method to Create New Product
        public IActionResult Create()
        {
            ViewData["ProductTypeId"] = new SelectList(db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["SpecialTagsId"] = new SelectList(db.SpecialTags.ToList(), "Id", "specialtagname");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [System.Obsolete]
        public async Task<IActionResult> Create(Products product, IFormFile image)
        {
            if (image != null)
            {
                var name = Path.Combine(_he.WebRootPath + "/Images",
                    Path.GetFileName(image.FileName));
                await image.CopyToAsync(new FileStream(name, FileMode.Create));
                product.Image = "/Images/" + image.FileName;
            }
            if (image == null)
            {
                product.Image = "Images/noimage.PNG";
            }
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }


        // Action Method to Edit Products
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            ViewData["ProductTypeId"] = new SelectList(db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["SpecialTagsId"] = new SelectList(db.SpecialTags.ToList(), "Id", "specialtagname");
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, Products product)
        {
            if (ModelState.IsValid)
            {
                db.Update(product);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // Action Method to check Details of the Product
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                id = 2;
            }
            var product = db.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            ViewData["ProductTypeId"] = new SelectList(db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["SpecialTagsId"] = new SelectList(db.SpecialTags.ToList(), "Id", "specialtagname");
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details()
        {
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShop/Areas/Admin/Controllers/ProductTypesController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypesController : Controller
    {
        private ApplicationDbContext _db;

        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.ProductTypes.ToList());
        }

        // Action method to Create new product type

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Add(productTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }

        // Action method to Edit product type
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var producttype = _db.ProductTypes.Find(id);
            if (producttype == null)
            {
                return NotFound();
            }
            return View(producttype);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Update(productTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }

        // Action method to show Details product type
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var producttype = _db.ProductTypes.Find(id);
            if (producttype == null)
            {
                return NotFound();
            }
            return View(producttype);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ProductTypes productTypes)
        {
            return RedirectToAction(nameof(Index));
        }
        // Action method to Delete product type
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var producttype = _db.ProductTypes.Find(id);
            if (producttype == null)
            {
                return NotFound();
            }
            return View(producttype);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, ProductTypes productTypes)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != productTypes.Id)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }
    }
}

OnlineShop/Areas/Admin/Controllers/SpecialTagsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialTagsController : Controller
    {
        private ApplicationDbContext db;
        public SpecialTagsController(ApplicationDbContext _db)
        {
            db = _db;
        }
        public IActionResult Index()
        {
            return View(db.SpecialTags.ToList());
        }

        // Action Method to Create new Tag
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTags specialTags )
        {
            if (ModelState.IsValid)
            {
                db.SpecialTags.Add(specialTags);
                await db.SaveChangesAsync();
                TempData["save"] = "Special tag has been added successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }

        // Action Method to Edit Special Tags
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                NotFound();
            }
            var tags = db.SpecialTags.Find(id);
            if (tags == null)
            {
                return NotFound();
            }
            return View(tags);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SpecialTags tags)
        {
            if (ModelState.IsValid)
            {
                db.Update(tags);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tags);
        }

        // Action Method to get details of Special tags
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var tag = db.SpecialTags.Find(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(SpecialTags specialTags)
        {
            return RedirectToAction(nameof(Index));
        }
        // Action Method to Delete Special tags
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var tag = db.SpecialTags.Find(id);
            if (tag==null)
            {
                return NotFound();
            }
            return View(tag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id,SpecialTags specialTags)
        {

            if (id == null)
            {
                return NotFound();
            }
            if (specialTags.Id != id)
            {
                return NotFound();
            }
            var tag = db.SpecialTags.Find(id);
            if (tag == null)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                db.Remove(tag);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

OnlineShop/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<td style="width: 150px;">
    <div class="btn-group">
        <a asp-action="Edit"  asp-area="Admin" class="btn btn-primary" asp-route-id="@Model"><i class="far fa-edit"></i></a>
        <a asp-action="Details"  asp-area="Admin" class="btn btn-info" asp-route-id="@Model"> <i class="fas fa-list-ul"></i> </a>
        <a asp-action="Delete"  asp-area="Admin" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash"></i></a>
    </div>
</td>

OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Special Types</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>